-- ============================================================================
--  Voter Address Check — Supabase access-control setup
--  Run this ONCE in the Supabase dashboard:  SQL Editor → New query → paste →
--  Run.  Safe to re-run (idempotent).
--
--  What it does:
--   * Locks the `pledges` table so the PUBLIC anon key can INSERT (the petition
--     form) but can NEVER read rows (no voter PII leaks through the public key).
--   * Keeps the public progress counter working via a function that returns
--     ONLY the number, never the rows.
--   * Creates an `admins` table. Only signed-in users listed there can read
--     pledges.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. Make sure the pledges table exists (no-op if you already created it).
--    Adjust column types only if yours differ; this matches the petition form.
-- ---------------------------------------------------------------------------
create table if not exists public.pledges (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz default now(),
  timestamp         text,
  campaign_id       text,
  full_name         text,
  email             text,
  address           text,
  city_key          text,
  city_display      text,
  voters_at_address integer,
  phone             text,
  consent           boolean,
  signature         text,
  source            text,
  inside_boundary   boolean
);

-- ---------------------------------------------------------------------------
-- 1. Turn on Row-Level Security. With RLS on and no permissive policy,
--    the default is DENY — nobody can touch the table until a policy allows it.
-- ---------------------------------------------------------------------------
alter table public.pledges enable row level security;

-- ---------------------------------------------------------------------------
-- 2. Allow the public (anon) key to INSERT pledges — and nothing else.
--    No SELECT/UPDATE/DELETE policy for anon = the public key cannot read,
--    edit, or delete any pledge.
-- ---------------------------------------------------------------------------
drop policy if exists "anon can insert pledges" on public.pledges;
create policy "anon can insert pledges"
  on public.pledges
  for insert
  to anon
  with check (true);

-- ---------------------------------------------------------------------------
-- 3. Admins registry. A signed-in user is an admin iff their auth id is here.
-- ---------------------------------------------------------------------------
create table if not exists public.admins (
  user_id  uuid primary key references auth.users(id) on delete cascade,
  email    text,
  added_at timestamptz default now()
);

alter table public.admins enable row level security;

-- A signed-in user may read their OWN admin row (needed for the is_admin check).
drop policy if exists "user reads own admin row" on public.admins;
create policy "user reads own admin row"
  on public.admins
  for select
  to authenticated
  using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- 4. is_admin() — SECURITY DEFINER so it can check membership without the
--    caller needing direct table rights, and without RLS recursion.
-- ---------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

grant execute on function public.is_admin() to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. Admins (signed in) may READ every pledge. This is the only path to the
--    actual voter data, and it requires a real authenticated admin session.
-- ---------------------------------------------------------------------------
drop policy if exists "admins can read pledges" on public.pledges;
create policy "admins can read pledges"
  on public.pledges
  for select
  to authenticated
  using (public.is_admin());

-- ---------------------------------------------------------------------------
-- 6. Public progress counter. SECURITY DEFINER bypasses RLS but returns ONLY
--    an integer, never any row. The home page calls this instead of reading
--    the table.
-- ---------------------------------------------------------------------------
create or replace function public.get_pledge_count()
returns integer
language sql
security definer
set search_path = public
as $$
  select count(*)::int from public.pledges;
$$;

grant execute on function public.get_pledge_count() to anon, authenticated;

-- ============================================================================
--  AFTER RUNNING THIS:
--
--  A) Create your admin login (Supabase dashboard → Authentication → Users →
--     "Add user" → set email + password, and tick "Auto Confirm User").
--
--  B) Promote that user to admin. Run this with YOUR email:
--
--       insert into public.admins (user_id, email)
--       select id, email from auth.users where email = 'you@example.com'
--       on conflict (user_id) do nothing;
--
--  C) Log in at /login.html with that email/password to reach /admin.html.
--
--  To add more admins later, repeat A + B for each person.
--  To revoke someone:  delete from public.admins where email = 'them@x.com';
-- ============================================================================
